(defun color-theme-crl-256()
  (interactive)
  (color-theme-install
   '(color-theme-crl
     ((background-color . "#121212")
      (background-mode . light)
      (border-color . "#0000af")
      (cursor-color . "#ffffff")
      (foreground-color . "#ffffff")
      (mouse-color . "#000000"))
     (fringe ((t (:background "#1c1c1c"))))
     (mode-line ((t (:foreground "#000000" :background "#e4e4e4"))))
     (region ((t (:background "#423c38"))))
     (font-lock-builtin-face ((t (:foreground "#ffaf00" :bold t))))
     (font-lock-comment-face ((t (:foreground "#b2b2b2" :italic t))))
     (font-lock-constant-face ((t (:foreground "#00d7ff"))))
     (font-lock-function-name-face ((t (:foreground "#ff5f00" :bold t))))
     (font-lock-keyword-face ((t (:foreground "#ffaf00"))))
     (font-lock-string-face ((t (:foreground "#ffff00"))))
     (font-lock-type-face ((t (:foreground "#ffffff" :bold t))))
     (font-lock-variable-name-face ((t (:foreground "#ffffff"))))
     (minibuffer-prompt ((t (:foreground "#ffffff" :bold t))))
     (font-lock-warning-face ((t (:foreground "ff0000" :bold t))))
     )))
(provide 'color-theme-crl)
